/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perseablue;

import java.awt.HeadlessException;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dinz
 */
public class halaman_admin extends javax.swing.JFrame {

    /**
     * Creates new form halaman_admin
     */
    public halaman_admin() {
        initComponents();
        tampil_table(); // Memanggil metode untuk menampilkan data di tabel
        IDfield.setText(String.valueOf(getNextId())); // Mengisi field ID dengan ID baru
    }

    private int getNextId() {
        int nextId = 1; // Default ID jika belum ada data
        try {
            Connection conn = koneksidb.configDB();
            String sql = "SELECT MAX(id_pertandingan) AS maxId FROM data_jadwal_pertandingan";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nextId = rs.getInt("maxId") + 1; // Menambahkan 1 ke ID terakhir
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return nextId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Pertandinganfield = new javax.swing.JTextField();
        Stadionfield = new javax.swing.JTextField();
        Tanggalfield = new javax.swing.JTextField();
        Jamfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tambahp = new javax.swing.JButton();
        Ubahp = new javax.swing.JButton();
        Hapusp = new javax.swing.JButton();
        Bersihkanp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablep = new javax.swing.JTable();
        homebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manajemen Jadwal Pertandingan");
        setBackground(new java.awt.Color(0, 1, 36));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 1, 36));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jam");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        IDfield.setEditable(false);
        IDfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDfieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pertandingan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stadion");

        Tambahp.setText("Tambah");
        Tambahp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahpActionPerformed(evt);
            }
        });

        Ubahp.setText("Ubah");
        Ubahp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahpActionPerformed(evt);
            }
        });

        Hapusp.setText("Hapus");
        Hapusp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapuspActionPerformed(evt);
            }
        });

        Bersihkanp.setText("Bersihkan");
        Bersihkanp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihkanpActionPerformed(evt);
            }
        });

        Tablep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Pertandingan", "Stadion", "Tanggal", "Jam"
            }
        ));
        Tablep.setEnabled(false);
        Tablep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablepMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tablep);

        homebtn.setText("Home");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Pertandinganfield, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stadionfield, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tanggalfield, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                    .addComponent(Jamfield)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Tambahp)
                        .addGap(45, 45, 45)
                        .addComponent(Ubahp)
                        .addGap(38, 38, 38)
                        .addComponent(Hapusp)
                        .addGap(40, 40, 40)
                        .addComponent(Bersihkanp)
                        .addGap(153, 153, 153)))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homebtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homebtn)
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(Stadionfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(Pertandinganfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Tanggalfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Jamfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bersihkanp)
                            .addComponent(Hapusp)
                            .addComponent(Ubahp)
                            .addComponent(Tambahp)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void IDfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDfieldActionPerformed

    private void TablepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablepMouseClicked
        // TODO add your handling code here:
        try {
            int baris = Tablep.rowAtPoint(evt.getPoint());

            // Ambil nilai dari tabel dan cek validitasnya
            Object idobj = Tablep.getValueAt(baris, 1);
            String id = idobj != null ? idobj.toString() : "";
            IDfield.setText(id); 
            
             Object pertandinganobj = Tablep.getValueAt(baris, 2);
            String pertandingan = pertandinganobj != null ? pertandinganobj.toString() : "";
            Pertandinganfield.setText(pertandingan);
         
            Object stadionobj = Tablep.getValueAt(baris, 3);
            String stadion = stadionobj != null ? stadionobj.toString() : "";
            Stadionfield.setText(stadion);
            
            Object tanggalobj = Tablep.getValueAt(baris, 4);
            String tanggal = tanggalobj != null ? tanggalobj.toString() : "";
            Tanggalfield.setText(tanggal);
            
            Object jamobj = Tablep.getValueAt(baris, 5);
            String jam = jamobj != null ? jamobj.toString() : "";
            Jamfield.setText(jam);
           
            
} catch (Exception e) {   
}
    }//GEN-LAST:event_TablepMouseClicked

    private void HapuspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapuspActionPerformed
    Hapus(); 
    // TODO add your handling code here:
    }//GEN-LAST:event_HapuspActionPerformed

    private void BersihkanpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihkanpActionPerformed
        // TODO add your handling code here:
        Bersihkanp();
    }//GEN-LAST:event_BersihkanpActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new dashboardAdmin().setVisible(true);
    }//GEN-LAST:event_homebtnActionPerformed

    private void TambahpActionPerformed(java.awt.event.ActionEvent evt) {
        String pertandingan = Pertandinganfield.getText();
        String stadion = Stadionfield.getText();
        String tanggal = Tanggalfield.getText();
        String jam = Jamfield.getText();
        try {
            Connection conn = koneksidb.configDB();
            String sql = "INSERT INTO data_jadwal_pertandingan (pertandingan, stadion, tanggal, jam) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, pertandingan);
            pst.setString(2, stadion);
            pst.setString(3, tanggal);
            pst.setString(4, jam);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
            tampil_table(); // Memperbarui tampilan tabel
            resetForm(); // Reset form setelah menambah data
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void UbahpActionPerformed(java.awt.event.ActionEvent evt) {
        String id_pertandingan = IDfield.getText(); // Pastikan ini hanya digunakan untuk WHERE clause
        String pertandingan = Pertandinganfield.getText();
        String stadion = Stadionfield.getText();
        String tanggal = Tanggalfield.getText();
        String jam = Jamfield.getText();
        try {
            Connection conn = koneksidb.configDB();
            String sql = "UPDATE data_jadwal_pertandingan SET pertandingan=?, stadion=?, tanggal=?, jam=? WHERE id_pertandingan=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, pertandingan);
            pst.setString(2, stadion);
            pst.setString(3, tanggal);
            pst.setString(4, jam);
            pst.setString(5, id_pertandingan);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            tampil_table(); // Memperbarui tampilan tabel
            resetForm(); // Reset form setelah update
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
 private void tampil_table() {
    try {
        Connection conn = koneksidb.configDB();
        String sql = "SELECT * FROM data_jadwal_pertandingan";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        // Membuat model tabel dengan kolom "No" yang akan diisi secara otomatis
        DefaultTableModel model = new DefaultTableModel(new String[]{"No", "id_pertandingan", "Pertandingan", "Stadion", "Tanggal", "Jam"}, 0);
        int noUrut = 1; // Variabel untuk nomor urut
        
        while (rs.next()) {
            String id_pertandingan = rs.getString("id_pertandingan");
            String pertandingan = rs.getString("Pertandingan");
            String stadion = rs.getString("Stadion");
            String tanggal = rs.getString("Tanggal");
            String jam = rs.getString("Jam");
            model.addRow(new Object[]{noUrut, id_pertandingan, pertandingan, stadion, tanggal, jam});
            noUrut++; // Menambahkan nomor urut setiap kali loop
        }
        Tablep.setModel(model);
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}

    private void Hapus() {
        String id_pertandingan = IDfield.getText();
        try {
            Connection conn = koneksidb.configDB();
            String sql = "DELETE FROM data_jadwal_pertandingan WHERE id_pertandingan=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, id_pertandingan);
            pst.executeUpdate();
            int response = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus Jadwal Pertandingan Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            tampil_table(); // Memperbarui tampilan tabel
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void resetForm() {
        Pertandinganfield.setText("");
        Stadionfield.setText("");
        Tanggalfield.setText("");
        Jamfield.setText("");
        IDfield.setText(String.valueOf(getNextId())); // Reset ID ke next increment
    }

    private void Bersihkanp() {
        // Dialog untuk debugging
        JOptionPane.showMessageDialog(null, "Bersihkan button clicked");

        // Mengosongkan semua field kecuali IDfield
        Pertandinganfield.setText("");
        Stadionfield.setText("");
        Tanggalfield.setText("");
        Jamfield.setText("");
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bersihkanp;
    private javax.swing.JButton Hapusp;
    private javax.swing.JTextField IDfield;
    private javax.swing.JTextField Jamfield;
    private javax.swing.JTextField Pertandinganfield;
    private javax.swing.JTextField Stadionfield;
    private javax.swing.JTable Tablep;
    private javax.swing.JButton Tambahp;
    private javax.swing.JTextField Tanggalfield;
    private javax.swing.JButton Ubahp;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
