/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perseablue;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akfal Shamid Y
 */
public class pemesananTiket extends javax.swing.JFrame {

    /**
     * Creates new form pemesananTiket
     */
    public pemesananTiket() {
        initComponents();
        tampil_table();
        tampil_table_tribun();
    }

      private void tampil_table(){
        DefaultTableModel tb = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // All cells are not editable
            }
        };
        tb.addColumn("No");
        tb.addColumn("Nomor Identitas");
        tb.addColumn("Nama");
        tb.addColumn("Email");
        tb.addColumn("Nomor Hp");
        tb.addColumn("Jumlah");
        tb.addColumn("Tribun");
        tb.addColumn("Pertandingan");
        tb.addColumn("Id Pertandingan");
        
        
        try {
            int counter =1;
            String query = "SELECT * FROM data_pesanan";
             Connection koneksi = (Connection)koneksidb.configDB();
             PreparedStatement state = koneksi.prepareStatement(query);
             ResultSet Result = state.executeQuery(query);
             while (Result.next()){
                 tb.addRow(new Object[]{
                     counter++,Result.getString(7), Result.getString(2),Result.getString(3),Result.getString(4), Result.getString(5),Result.getString(6),Result.getString(10),Result.getString(9),
                 });
             }
            tabelPemesananTiket.setModel(tb);
        }catch (Exception e){
            
        }
        
    }
      private void tampil_table_tribun(){
        DefaultTableModel tb = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // All cells are not editable
            }
        };
        tb.addColumn("No");
        tb.addColumn("Tribun");
        tb.addColumn("Harga");
        try {
            int counter =1;
            String query = "SELECT * FROM data_tribun";
             Connection koneksi = (Connection)koneksidb.configDB();
             PreparedStatement state = koneksi.prepareStatement(query);
             ResultSet Result = state.executeQuery(query);
             while (Result.next()){
                 tb.addRow(new Object[]{
                     counter++,Result.getString(2), Result.getString(3),
                 });
             }
            tabelTribun.setModel(tb);
        }catch (Exception e){
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layar = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputNomorHp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        inputNomorIdentitas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPemesananTiket = new javax.swing.JTable();
        inputJumlah = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelTribun = new javax.swing.JTable();
        inputTribun = new javax.swing.JTextField();
        inputHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputIdPertandingan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemesanan Tiket");

        layar.setBackground(new java.awt.Color(255, 255, 255));
        layar.setPreferredSize(new java.awt.Dimension(1000, 975));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(802, 1000));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1000));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Email");

        inputEmail.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("No Hp");

        inputNomorHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomorHpActionPerformed(evt);
            }
        });

        jButton1.setText("Pesan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tribun");

        inputNomorIdentitas.setEditable(false);
        inputNomorIdentitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomorIdentitasActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("No");

        tabelPemesananTiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPemesananTiket.setMinimumSize(new java.awt.Dimension(20, 80));
        tabelPemesananTiket.setPreferredSize(new java.awt.Dimension(20, 80));
        tabelPemesananTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemesananTiketMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPemesananTiket);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("jumlah");

        tabelTribun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTribun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTribunMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelTribun);

        inputTribun.setEditable(false);
        inputTribun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTribunActionPerformed(evt);
            }
        });

        inputHarga.setEditable(false);
        inputHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHargaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Harga");

        inputIdPertandingan.setEditable(false);
        inputIdPertandingan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdPertandinganActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("ID Pertandingan ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(32, 32, 32)
                                        .addComponent(inputNomorHp, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(31, 31, 31)
                                        .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inputNomorIdentitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(35, 35, 35)
                                        .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(32, 32, 32)
                                        .addComponent(inputTribun, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(inputIdPertandingan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(inputNomorIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputIdPertandingan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputNomorHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputTribun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(40, 50, 710, 660);

        jScrollPane1.setViewportView(jPanel1);

        layar.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layarLayout = new javax.swing.GroupLayout(layar);
        layar.setLayout(layarLayout);
        layarLayout.setHorizontalGroup(
            layarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layarLayout.setVerticalGroup(
            layarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Profile");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layar, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomorHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomorHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomorHpActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputNomorIdentitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomorIdentitasActionPerformed
        // TODO add your handling code here:
        String Nama = inputNama.getText();
        String No = inputNomorIdentitas.getText();
        try{
        String QueryPesan = "SELECT nama FROM data_pesanan WHERE no= '"+No+"'";
        java.sql.Connection koneksi = (java.sql.Connection)koneksidb.configDB();
            //Kirim Paramater java ke sql
            java.sql.PreparedStatement SQL =koneksi.prepareStatement(QueryPesan);
            //eksekusi Query
            SQL.execute(); 
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Dinputkan");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_inputNomorIdentitasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String NomorIdentitas = inputNomorIdentitas.getText();
        String Nama = inputNama.getText();
        String NoHp = inputNomorHp.getText();
        String Jumlah = Integer.toString((Integer) inputJumlah.getValue());
        String Tribun = inputTribun.getText();
        String Tanding = inputIdPertandingan.getText();
        String Harga = inputHarga.getText();
        try {
            if (NomorIdentitas.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Field tidak boleh ada yang kosong!");
            } else {
                // Menghubungkan java dan sql
                Connection koneksi = (Connection) koneksidb.configDB();

                // Query untuk memeriksa apakah email atau NIK sudah ada
                String sqlCheck = "SELECT COUNT(*) FROM data_pesanan WHERE nomorIdentitas = ? AND id_pertandingan= ?";

                // Siapkan pernyataan SQL yang telah dikompilasi sebelumnya untuk eksekusi
                PreparedStatement query_check = koneksi.prepareStatement(sqlCheck);

                // Setel parameter dalam query
                query_check.setString(1, NomorIdentitas);
                query_check.setString(2, Tanding);

                // Eksekusi query dan simpan hasilnya dalam objek ResultSet
                ResultSet result = query_check.executeQuery();
                result.next();  // Pindahkan ke baris pertama hasil

                // If the query result indicates that the identity number for this match is already registered
                if (result.getInt(1) > 0) {
                    String QueryPesan = "UPDATE data_pesanan SET nama='"+Nama+"', nomorHp='"+NoHp+"', jumlah='"+Jumlah+"', tribun='"+Tribun+"',  harga='"+Harga+"' WHERE nomorIdentitas='"+NomorIdentitas+"' AND id_pertandingan='"+Tanding+"';";
                    
                 
                    java.sql.Connection PenghubungDatabase = (java.sql.Connection)koneksidb.configDB();
                    java.sql.PreparedStatement SQL = PenghubungDatabase.prepareStatement(QueryPesan);
                    SQL.execute();
                    
                    SQL.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diinputkan");
                    this.setVisible(false);
                    new authPembayaran().setVisible(true);
                    // Tampilkan pesan bahwa email atau NIK sudah terdaftar
                } else {
                    JOptionPane.showMessageDialog(null, "No Identitas pada pertandingan ini sudah terdaftar. Silakan gunakan yang lain.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dinputkan");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelPemesananTiketMouseClicked(java.awt.event.MouseEvent evt) {
        try {
            int baris = tabelPemesananTiket.rowAtPoint(evt.getPoint());
            if (baris != -1) {
                Object noObj = tabelPemesananTiket.getValueAt(baris, 1);
                inputNomorIdentitas.setText(noObj != null ? noObj.toString() : "");
    
                Object nmObj = tabelPemesananTiket.getValueAt(baris, 2);
                inputNama.setText(nmObj != null ? nmObj.toString() : "");
    
                Object emailObj = tabelPemesananTiket.getValueAt(baris, 3);
                inputEmail.setText(emailObj != null ? emailObj.toString() : "");
    
                Object noHpObj = tabelPemesananTiket.getValueAt(baris, 4);
                inputNomorHp.setText(noHpObj != null ? noHpObj.toString() : "");
    
                Object jmlhObj = tabelPemesananTiket.getValueAt(baris, 5);
                inputJumlah.setValue(jmlhObj != null ? Integer.parseInt(jmlhObj.toString()) : 0);
    
                Object tribObj = tabelPemesananTiket.getValueAt(baris, 6);
                inputTribun.setText(tribObj != null ? tribObj.toString() : "");
    
                Object idTandingObj = tabelPemesananTiket.getValueAt(baris, 8);
                inputIdPertandingan.setText(idTandingObj != null ? idTandingObj.toString() : "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void tabelTribunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTribunMouseClicked
        // TODO add your handling code here:
           try {
               int baris = tabelTribun.rowAtPoint(evt.getPoint());
               String trib = tabelTribun.getValueAt(baris,1).toString();
               inputTribun.setText(trib);
               String harga = tabelTribun.getValueAt(baris,2).toString();
               inputHarga.setText(harga);
               
               
           } catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
           }
    }//GEN-LAST:event_tabelTribunMouseClicked

    private void inputTribunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTribunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTribunActionPerformed

    private void inputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHargaActionPerformed

    private void inputIdPertandinganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdPertandinganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdPertandinganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesananTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesananTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesananTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesananTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesananTiket().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputIdPertandingan;
    private javax.swing.JSpinner inputJumlah;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNomorHp;
    private javax.swing.JTextField inputNomorIdentitas;
    private javax.swing.JTextField inputTribun;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDesktopPane layar;
    private javax.swing.JTable tabelPemesananTiket;
    private javax.swing.JTable tabelTribun;
    // End of variables declaration//GEN-END:variables
}
