/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perseablue;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN11
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        cancelbtn = new javax.swing.JButton();
        registEmail = new javax.swing.JTextField();
        registjk = new javax.swing.JComboBox<>();
        nomorHP = new javax.swing.JLabel();
        registPass = new javax.swing.JPasswordField();
        registNohp = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        jenisKelamin = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        registAlamat = new javax.swing.JTextField();
        nomorIdentitas = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        registNoidentitas = new javax.swing.JTextField();
        registNama = new javax.swing.JTextField();
        fregistbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true), "PERSEABLUE REGISTER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        email.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");

        cancelbtn.setBackground(new java.awt.Color(255, 102, 102));
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        registEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registEmailActionPerformed(evt);
            }
        });

        registjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        nomorHP.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        nomorHP.setForeground(new java.awt.Color(255, 255, 255));
        nomorHP.setText("Nomor HP");

        registNohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registNohpActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");

        jenisKelamin.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jenisKelamin.setForeground(new java.awt.Color(255, 255, 255));
        jenisKelamin.setText("Jenis Kelamin");

        alamat.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setText("Alamat");

        registAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registAlamatActionPerformed(evt);
            }
        });

        nomorIdentitas.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        nomorIdentitas.setForeground(new java.awt.Color(255, 255, 255));
        nomorIdentitas.setText("NIK/Paspor");

        nama.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Nama");

        registNoidentitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registNoidentitasActionPerformed(evt);
            }
        });

        registNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registNamaActionPerformed(evt);
            }
        });

        fregistbtn.setBackground(new java.awt.Color(0, 0, 153));
        fregistbtn.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        fregistbtn.setForeground(new java.awt.Color(255, 255, 255));
        fregistbtn.setText("Register");
        fregistbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fregistbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fregistbtn))
                    .addComponent(nomorIdentitas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jenisKelamin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorHP, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registNama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registNohp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registNoidentitas)
                    .addComponent(registjk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registPass, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomorHP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jenisKelamin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registjk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomorIdentitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registNoidentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fregistbtn)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registNamaActionPerformed

    private void registEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registEmailActionPerformed

    private void registNohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registNohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registNohpActionPerformed

    private void registAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registAlamatActionPerformed

    private void registNoidentitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registNoidentitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registNoidentitasActionPerformed

    private void fregistbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fregistbtnActionPerformed
        // TODO add your handling code here:
        try {
            // Mengambil input dari form
            String nama = registNama.getText();
            String email = registEmail.getText();
            String noHP = registNohp.getText();
            String pass = registPass.getText();
            String JK = (String) registjk.getSelectedItem();
            String alamat = registAlamat.getText();
            String NoIdentitas = registNoidentitas.getText();

            // Memastikan semua field telah diisi
            if (nama.isEmpty() || email.isEmpty() || noHP.isEmpty() || pass.isEmpty() || JK.isEmpty() || alamat.isEmpty() || NoIdentitas.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Field tidak boleh ada yang kosong!");
            } else {
                // Menghubungkan java dan sql
                Connection koneksi = (Connection) koneksidb.configDB();

                // Query untuk memeriksa apakah email atau NIK sudah ada
                String sqlCheck = "SELECT COUNT(*) FROM data_users WHERE email = ? OR nomorIdentitas = ?";

                // Siapkan pernyataan SQL yang telah dikompilasi sebelumnya untuk eksekusi
                PreparedStatement query_check = koneksi.prepareStatement(sqlCheck);

                // Setel parameter dalam query
                query_check.setString(1, email);
                query_check.setString(2, NoIdentitas);

                // Eksekusi query dan simpan hasilnya dalam objek ResultSet
                ResultSet result = query_check.executeQuery();
                result.next();  // Pindahkan ke baris pertama hasil

                // Jika hasil query menunjukkan bahwa email atau NoIdentitas sudah ada di database
                if (result.getInt(1) > 0) {
                    // Tampilkan pesan bahwa email atau NIK sudah terdaftar
                    JOptionPane.showMessageDialog(null, "Email atau No Identitas sudah terdaftar. Silakan gunakan yang lain.");
                    bersih_layar();
                } else {
                    // Jika email atau NIK belum ada, siapkan query untuk memasukkan data baru ke dalam tabel data_users
                    String sqlInsert = "INSERT INTO data_users VALUES (?, ?, ?, ?, ?, ?, ?)";

                    // Siapkan pernyataan SQL yang telah dikompilasi sebelumnya untuk eksekusi
                    PreparedStatement query_insert = koneksi.prepareStatement(sqlInsert);

                    // Setel parameter dalam query insert
                    query_insert.setString(1, nama);
                    query_insert.setString(2, email);
                    query_insert.setString(3, noHP);
                    query_insert.setString(4, pass);
                    query_insert.setString(5, JK);
                    query_insert.setString(6, alamat);
                    query_insert.setString(7, NoIdentitas);

                    // Eksekusi perintah SQL
                    query_insert.execute();

                    // Validasi SQL jika berhasil 
                    JOptionPane.showMessageDialog(null, "Registrasi Berhasil! Silahkan Lakukan Login");
                    this.setVisible(false);
                    new login().setVisible(true);
                }
            }

        } catch (Exception e) {
            // Pesan error jika ada kesalahan
            JOptionPane.showMessageDialog(null, "Kesalahan: " + e);
        }
    }//GEN-LAST:event_fregistbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_cancelbtnActionPerformed

    public void bersih_layar(){
        registNama.setText("");
        registEmail.setText("");
        registNohp.setText("");
        registPass.setText("");
        registjk.setSelectedIndex(0);
        registAlamat.setText("");
        registNoidentitas.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel email;
    private javax.swing.JButton fregistbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jenisKelamin;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nomorHP;
    private javax.swing.JLabel nomorIdentitas;
    private javax.swing.JLabel password;
    private javax.swing.JTextField registAlamat;
    private javax.swing.JTextField registEmail;
    private javax.swing.JTextField registNama;
    private javax.swing.JTextField registNohp;
    private javax.swing.JTextField registNoidentitas;
    private javax.swing.JPasswordField registPass;
    private javax.swing.JComboBox<String> registjk;
    // End of variables declaration//GEN-END:variables
}
