/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perseablue;

import java.util.Random;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN11
 */
public class sendCode extends javax.swing.JFrame {
    int randomCode;

    /**
     * Creates new form sendCode
     */
    public sendCode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtVerify = new javax.swing.JTextField();
        sendCodebtn = new javax.swing.JButton();
        verifyCodebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true), "PERSEABLUE RESET PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Verify Code");

        txtEmail.setPreferredSize(new java.awt.Dimension(68, 30));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtVerify.setMinimumSize(new java.awt.Dimension(68, 30));
        txtVerify.setPreferredSize(new java.awt.Dimension(68, 31));

        sendCodebtn.setBackground(new java.awt.Color(0, 0, 153));
        sendCodebtn.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        sendCodebtn.setForeground(new java.awt.Color(255, 255, 255));
        sendCodebtn.setText("Send Code");
        sendCodebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCodebtnActionPerformed(evt);
            }
        });

        verifyCodebtn.setBackground(new java.awt.Color(0, 0, 153));
        verifyCodebtn.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        verifyCodebtn.setForeground(new java.awt.Color(255, 255, 255));
        verifyCodebtn.setText("Verify");
        verifyCodebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyCodebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendCodebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verifyCodebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sendCodebtn)
                        .addGap(56, 56, 56)
                        .addComponent(verifyCodebtn)))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verifyCodebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyCodebtnActionPerformed
        // TODO add your handling code here:
        // check verify code
        // jika berhasli, tampilkan pesan
        // JOptionPane.showMessageDialog(null, "Kode Sesuai, Silahkan Reset Password anda")
        if(Integer.valueOf(txtVerify.getText()) == randomCode){
            resetPass rs = new resetPass(txtEmail.getText());
            rs.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Kode Reset Tidak Sesuai");
        }
        
    }//GEN-LAST:event_verifyCodebtnActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void sendCodebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendCodebtnActionPerformed
        // TODO add your handling code here:
        try {
            Random rand = new Random(); // Membuat objek Random untuk menghasilkan angka acak
            randomCode = rand.nextInt(999999); // Menghasilkan angka acak antara 0 dan 999999 untuk kode reset
            String host = "smtp.gmail.com"; // Host server SMTP Gmail
            String user = "perseablue6@gmail.com"; // Email pengirim
            String pass = "wxbs pohn gwbx jqxr"; // App password untuk email pengirim
            String to = txtEmail.getText(); // Mendapatkan email penerima dari input pengguna
            String subject = "Resetting Code Perseablue"; // Subjek email
            String message = "Kode reset password kamu adalah " + randomCode; // Pesan email berisi kode reset
            boolean sessionDebug = false; // Menonaktifkan debug session

            Properties pros = System.getProperties(); // Mendapatkan properti sistem
            pros.put("mail.smtp.starttls.enable", "true"); // Mengaktifkan STARTTLS
            pros.put("mail.smtp.host", "smtp.gmail.com"); // Menetapkan host SMTP
            pros.put("mail.smtp.port", "587"); // Menetapkan port SMTP
            pros.put("mail.smtp.auth", "true"); // Mengaktifkan autentikasi SMTP
            pros.put("mail.smtp.starttls.required", "true"); // STARTTLS diperlukan

            // Membuat sesi email dengan autentikasi
            Session mailSession = Session.getDefaultInstance(pros, new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(user, pass); // Menggunakan email dan app password untuk autentikasi
                }
            });

            mailSession.setDebug(sessionDebug); // Menonaktifkan debug session
            Message msg = new MimeMessage(mailSession); // Membuat objek pesan email
            msg.setFrom(new InternetAddress(user)); // Menetapkan alamat pengirim
            InternetAddress[] address = {new InternetAddress(to)}; // Menetapkan alamat penerima
            msg.setRecipients(Message.RecipientType.TO, address); // Menambahkan penerima ke pesan
            msg.setSubject(subject); // Menetapkan subjek email
            msg.setText(message); // Menetapkan isi pesan email

            // Mengirim email
            Transport transport = mailSession.getTransport("smtp"); // Mendapatkan transport SMTP
            transport.connect(host, user, pass); // Menghubungkan ke server SMTP
            transport.sendMessage(msg, msg.getAllRecipients()); // Mengirimkan pesan email ke semua penerima
            transport.close(); // Menutup koneksi transport
            JOptionPane.showMessageDialog(null, "Kode reset sudah dikirim ke email anda"); // Menampilkan pesan konfirmasi kepada pengguna

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_sendCodebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sendCodebtn;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtVerify;
    private javax.swing.JButton verifyCodebtn;
    // End of variables declaration//GEN-END:variables
}
